/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_about1 (void);
GtkWidget* create_prefswindow (void);
GtkWidget* create_colorselectiondialog1 (void);
GtkWidget* create_fullscreenwindow (void);
GtkWidget* create_shutdownwindow (void);
GtkWidget* create_fullscreenwindowprogressbar (void);
GtkWidget* create_calibratewindow (void);
